### ISSUE TITLE
Rules Hierarchy

### ISSUE THREAD

**Issue by n8chavez** [henrypp/simplewall#1206] opened 2022-04-15 06:01 UTC
Is there any way to have a hierarchy with simplewall? It would be nice to have a rule where an app can only communicate through a certain address, a sock5 proxy address, while also having every other connection blocked. But I cannot see a way to do that; if I create a block rule it takes priority over the allow rule(s) and doesn't allow any connection at all. I know it's not a limitation of wfp, because Sphinx's firewall WFC can do this.

**Comment by gettysburg** [comment] 2022-04-16 09:51
By enabling "Block outbound connections for all", nothing on your machine will be able to establish connections, not even to your LAN devices.

![image](https://user-images.githubusercontent.com/2256003/163669515-c7ec17cc-5d18-4f65-b750-911b86963e29.png)

Now, create a user-rule for the application using the SOCKS5 proxy, with the following parameters set:

```
Protocol: TCP
Family: IPv4
Direction: Outbound
Action: Allow
Rule (Remote): Exact IP and Port of your SOCKS5 proxy.
Apps: Choose your application using the proxy.
```

Finally, click save - the application should now be able to establish a connection. If not, use simplewall's logger to find the cause of the issue.

Please note that by enabling "Block outbound connections for all", you will have to create rules for all application that intend to connect to the internet. This does not bother me, since it also protects me from malware, spyware or freeware with built-in data collection functionality.

P.S: Please don't abuse the bug tracker to ask questions. This is not a problem with simplewall or your computer, but rather the person sitting in front of your computer - Just joking, we all make mistakes sometimes ✌️ 

I hope this configuration works for you, if it does, please close the ticket with a comment.

**Comment by Rexadev** [comment] 2022-04-24 06:37
Duplicate of https://github.com/henrypp/simplewall/issues/1156

**Comment by gettysburg** [comment] 2022-04-24 15:31
> Duplicate of #1156

Yes and no, what he wants to do can be done as described in my reply, thereby this ticket is solved (it shouldn't have existed in the first place since it is not a bug report, but people tend to abuse the bug tracker for questions and since this is not punished by Henry, it seems like he has no problem with it).

An actual hierarchy setting is possible and up to Henry or any other C developer to implement, just create a pull request 👍

**Comment by gettysburg** [comment] 2022-04-24 15:37
> Duplicate of #1156

Yes and no, as described in my reply, this is possible without implementing a hierarchy, thereby this ticket is solved (it shouldn't have existed in the first place since it is not a bug report, but people tend to abuse the bug tracker for questions and since this is not punished by Henry, it seems like he has no problem with it).

An actual hierarchy is possible and up to Henry or any other C developer familiar with the code base and WFP to implement, feel free to create a pull request 👍

**Comment by henrypp** [comment] 2022-06-24 09:17
It can be done without "hierarchy" in rules.

**Closed by henrypp** 2022-06-24 09:17 UTC
