### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by jonnaya** [henrypp/simplewall#1463] opened 2023-07-28 17:07 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7

### Windows version

Win 10 

### Steps to reproduce

It was random

### Actual behavior

Error exception message , random crash of simplewall. Downgraded to stable 3.6.7

**Comment by FiddleStickers** [comment] 2023-07-28 21:39
Same!!!
![Screenshot 2023-07-28 233738](https://github.com/henrypp/simplewall/assets/32528471/7bc7e0de-8ce6-4844-86c8-abccf769ed28)

**Comment by dlong500** [comment] 2023-07-29 03:35
Dupe of #1455.  Please actually search both open and closed issues.

**Comment by henrypp** [comment] 2023-07-29 07:41
#1455

**Closed by henrypp** 2023-07-29 07:41 UTC
Labels: duplicate
