### ISSUE TITLE
log.. Block Connections All Outbound.

### ISSUE THREAD

**Issue by oklokl** [henrypp/simplewall#945] opened 2021-06-04 23:08 UTC
![1](https://user-images.githubusercontent.com/1571600/120870634-626d4900-c5d4-11eb-8966-78d1a57b4bca.png)
![2](https://user-images.githubusercontent.com/1571600/120870645-66996680-c5d4-11eb-9dba-97f5befb1d2a.png)
In my case, I am using it with an existing Windows firewall.

Inbound Blocking.
But I am marked as outbound.
It was like that from the beginning.

Is that how policy works?
Or is it a bug?

Microsoft Windows [Version 10.0.19043.1023]
![3](https://user-images.githubusercontent.com/1571600/120870847-07882180-c5d5-11eb-82e8-5b4a764ffb47.png)
3.3.4 Version

Thank you. :)

**Comment by RikisX** [comment] 2021-06-05 21:55
![image](https://user-images.githubusercontent.com/5813374/120906342-5bd8e300-c661-11eb-89b4-5521e7a18c9b.png)
I noticed this too. If I check for my open ports ( https://www.yougetsignal.com/tools/open-ports/ ), log always says it's Outbound. It's confusing when you don't know if programs tries to connect to internet or just someone tries to connect to it.

**Comment by henrypp** [comment] 2021-06-15 04:13
I am lost in translation. Did not see where is the question.

**Comment by RikisX** [comment] 2021-06-15 06:35
Outbound and incoming connections both shows as "Outbound" in "Direction" column in log (same in notification).

**Comment by oklokl** [comment] 2021-06-15 08:51
I want to change to in-out. Suggestions.
:)
Outbound
Inbound

I hope it will be expressed in two forms.
Incoming connection.
Outgoing Connections

I'm sorry that I can't speak English.
My educational background is a little low. 
:)

**Comment by hushkamala** [comment] 2021-07-05 19:45
Hello,

I'm also experiencing this issue since version 3.2.4.

This is v3.2.4:
![v3 2 4](https://user-images.githubusercontent.com/72048073/124512581-a40a3300-ddd0-11eb-98ec-386585b78ece.jpg)

This is v3.3.4:
![v3 3 4](https://user-images.githubusercontent.com/72048073/124512636-c3a15b80-ddd0-11eb-99f3-15f9f0e84db9.jpg)

Both are described in the "Packets Log Tab" as a "BlockRecvAccept" Filter, but the Direction of the logged connection in v3.2.4 is correctly logged as Inbound. And on version 3.3.3, 3.3.4 and 3.3.5 it is logged as Outbound.

I hope my explanation is understandable.
Thanks for your work on SimpleWall.

**Comment by Alcazer** [comment] 2021-08-19 02:10
> Outbound and incoming connections both shows as "Outbound" in "Direction" column in log (same in notification).

@henrypp I checked simplewall.log and Packets Log tab, it's right.

**Comment by Alcazer** [comment] 2021-08-19 02:16
Duplicate of #935

**Closed** 2021-08-22 08:30 UTC
Labels: question
