### ISSUE TITLE
Feature Request - Allow/Block per "session"

### ISSUE THREAD

**Issue by LeafG** [henrypp/simplewall#796] opened 2020-10-11 05:08 UTC
Is it possible to allow or block access for an app not per minutes (as it works now), but also to add an option to allow/ block the app for "this" *session?

Example/ description:
I have a browser I use from time to time for tests. Its not my main one.

Sometimes, I want it to access the internet but at other times I need to test things without Internet access.
For the latter, I must keep closing SimpleWall alert dialog. This dialog keeps popping up and disturbs working.

Is such additional feature possible?
If not, is it possible to add time for the blocking, similar to the "allow" time?

*session: Meaning "this time only", not a browser session.

**Comment by pwn0r** [comment] 2020-10-13 10:58
the problem I guess here you need to define what you mean *exactly* by "for this session only"

**Comment by pwn0r** [comment] 2020-10-13 12:41
1sf of all, PM as a browser is too oldfag even for me, never understood the point in it, WATERfox all the way <3 I still use waterfox mainly because of ONE extension which development stopped (i.e. the dev did not convert it to web extensions as that probably required to redo it from scratch). 

2. That is exactly what I suspected. The session in your lingvo means process "session".  Means simplewall has to monitor running PIDs on the system and disable the filter as soon as such pid is closed.  Depends on the developer if he wants to implement this.

But have I got news for you. OK you are on PM so understandably out of touch with modern browsers :D 
They are now all-singing all-dancing all-RAM-eating multiprocess monsters (i run chromium + firefox normally, and about 2-3GB of RAM is usually consumed by them, despite a lot of configuration and optimisations which I enabled). Firefox since electrolysis merged into main branch, Chromium for a long while. Firefox has 4 processes by default as a minimum, and this can vary further during session. Every tab on chromium is a separate process.   And modern TOR versions are based on recent fox esr so would be same as mainline firefox. 

So in regards to browsers or other complicated softwares this PID monitoring would be quite a mess.

**Comment by TontyTon** [comment] 2020-10-29 00:57
@pwn0r AFAIK, in chrome only one process connects to the internet. And this is same for most applications.
And I think it doesn't matter if there is one process or hundred, as session for each process will be different.
But the problem is SW filter requests on the basis of file not the process, so for this feature to work, ig, whole program would have to be changed, but another requirement is WFP needs to support it, I think WFP don't supprt this.

**Closed** 2023-03-21 12:33 UTC
