### ISSUE TITLE
Boot time filters not working

### ISSUE THREAD

**Issue by TontyTon** [henrypp/simplewall#292] opened 2019-01-04 06:53 UTC
Boot time filters are not working. Filters start to work after some time of loading of simplewall. I tried this by blocking all apps including simplewall. 

I am even able to detect this in resource monitor, simplewall itself is able to check for updates.

I am on windows 10 laptop.

**Comment by TontyTon** [comment] 2019-01-25 12:33
@henrypp What about this?

**Comment by henrypp** [comment] 2019-01-25 12:41
- boot time filters is managed to prevent leaks before system started up (before logon ui displayed).
- simplewall filters are working even simplewall is not running, bacause filters are processed by `bfe` service.

i can not answer any other your question, because idk how you are configured simplewall.

**Comment by TontyTon** [comment] 2019-01-25 15:24
These are my settings
![1](https://user-images.githubusercontent.com/35778430/51753956-185d2a00-20e1-11e9-8800-e5fa83aa488a.PNG)
![2](https://user-images.githubusercontent.com/35778430/51753965-1dba7480-20e1-11e9-9a6f-af938635f742.PNG)

Filtering enabled with 'Whitelist(Allow Selected)' and no apps are selected.

Disabled all 'System rules' and 'User rules'. Except 'DNS' in 'System rules'

These are all the settings. According to these settings, internet access of all apps is disabled.

After these settings, I restarted my computer and saw that apps were able to connect to the internet.
They were able to connect till some time of start of Simplewall.

After that everything works correctly. Even after closing of SW.

**Comment by sun-shine-boy** [comment] 2019-01-30 07:19
maybe WFP/windows bug?

**Comment by TontyTon** [comment] 2019-01-30 13:36
yes, may be.
someone should also check this on their system.
Can you @sun-shine-boy ??

**Steps**

1.  Enable filtering with 'Whitelist(Allow Selected)' and no apps are selected.
2. Disable all 'System rules' and 'User rules'. Except 'DNS' in 'System rules'
3. Enable 'boot time filters', 'load on system startup' and 'skip uac prompt warning'.
4. restart system. (ensure if it is connected to internet or don't require any authentication or something else.  **Result should be that your computer connects to the internet much before the start of SW**)
5. start 'resource monitor' as soon as possible and check if anything is able to connect to the internet. 


You can also use 'Live TCP UDP Watch'(but remember it shows both connected and disabled apps, you have to check through 'Connections Count'). It will help know that if the apps were denied access or not.

**Comment by sun-shine-boy** [comment] 2019-01-30 23:32
Can't reproduce this issue here. I'm on admin Acc+UAC is completely disabled.
are you on standard acc? if yes have you UAC enabled? try with admin acc and UAC disabled.

**Comment by henrypp** [comment] 2019-01-31 03:38
> Result should be that your computer connects to the internet much before the start of SW)

Any proof? Like Process Hacker establised network connections screenshot

**Comment by DivAB** [comment] 2019-01-31 09:39
I tested with Windows Time service:
Changed Time (try at least 10 min to see immediate results). 
1. Blocked W32Time in simplewall - w32tm /resync error.
2. Allowed W32Time - w32tm /resync changed clock.
Changed Time again. Blocked W32Time in simplewall. Boot Time Filters on. Reboot.
Expected result: Still wrong time after reboot.
But: Time is synced - so Boot Time Filters cannot work.

**Comment by TontyTon** [comment] 2019-01-31 10:42
@henrypp Its not possible, because till we take screenshot simplewall has started.

**Comment by ltGuillaume** [comment] 2019-01-31 12:43
@DivAB Did you also block the "Windows Time" **service**?

**Comment by henrypp** [comment] 2019-01-31 15:37
> ....Boot Time Filters on.

i do not understand why boot time filters are tied up with w32time service, because i explained what boot-time filters is for.

> @henrypp Its not possible, because till we take screenshot simplewall has started.

this is i can not understand too, why you could not turn off "load at system startup" option.

and no one can provide any proof which any connection established.

**Comment by TontyTon** [comment] 2019-01-31 20:45
I didn't tried turning it off because thought that may be then there may be some different mechanism,but I tried just now. AND problem still persists.

Screenshot is from app 'Live TCP UDP watch'. It shows all connections(connected or dis-connected) for the time it is kept open. I opened the app just after my laptop(old piece) started responding, (nearly a minute after desktop is shown).
![capture](https://user-images.githubusercontent.com/35778430/52084077-3b974600-25c7-11e9-87de-7ff3fad49239.PNG)

**Comment by DivAB** [comment] 2019-02-01 08:33
@ltGuillaume: I stoped testing. I am in a network domain AD environment, so I cannot test to simply block all. But I tested on a VM Win10 and I could not reproduce it. If everything is blocked there is no time sync, also after reboot.

What I found out is, that if BFE service is not started for any reason (of course) the filters are not set, but simplewall still shows "filters enabled" - so you will not realise that they are not set. My BFE service was set to "manual" and simplewall (autostarts after reboot) does not start the service and it took me a while to realise that the filters are not set. Simplewall even logs this as an error in its logfile: FwpmEngineOpen(),0x000006d9,<empty>,2.3.13 but does not display a warning or change the status to "filters disabled". This will also happen if the services stops for any reason or crashes. You will not realise it, the filters are just gone.

It would be an improvement if simplewall would display a warning if the filters are not set and change its status to "filters disabled" or even better (if possible) to block all network connections until the BFE service is started and the filters are set.

**Comment by ltGuillaume** [comment] 2019-02-01 12:21
> What I found out is, that if BFE service is not started for any reason (of course) the filters are not set, but simplewall still shows "filters enabled" - so you will not realise that they are not set. My BFE service was set to "manual" and simplewall (autostarts after reboot) does not start the service and it took me a while to realise that the filters are not set. Simplewall even logs this as an error in its logfile: FwpmEngineOpen(),0x000006d9,,2.3.13 but does not display a warning or change the status to "filters disabled". This will also happen if the services stops for any reason or crashes. You will not realise it, the filters are just gone.

That is a good find and should be addressed indeed @henrypp

**Comment by ltGuillaume** [comment] 2019-02-02 04:53
@TontyTon Yes, simplewall.exe is just the GUI, the filters are not depending on it running or not. This is already known, _but_ it is exactly why the boot-time filters exist.

**Comment by TontyTon** [comment] 2019-02-02 10:42
According to henrypp

> boot time filters is managed to prevent leaks before system started up (before logon ui displayed)


_Now should I close this issue as it's not in control of SW_ or _Continue the issue to find the solution of leak before bfe service start_

**Comment by ltGuillaume** [comment] 2019-02-02 13:44
Well apparently it's not solved, is it? The boot-time filters aren't worth much _if_ your findings hold.

**Comment by TontyTon** [comment] 2019-02-02 15:37
Since, before the start of bfe service filters are not at work and pc is able to connect to the internet.
The problem is not solved, as suggested by DivAB
>(if possible) block all network connections until the BFE service is started and the filters are set.

But I doubt the possiblity, as MS's Tracking needs.

**Comment by DivAB** [comment] 2019-02-04 09:12
First of all I would suggest that SW does not just log critical errors silenty, but displays a message and changes its status from "filters enabled" to "filters disabled" because that is the actual condition. 

Second suggestion: SW disables internet access completely untill all filters are set and running, eg by registry or setting a proxy server to a non existing address until the conditions are met (or whatever better method). Of course this would mean that SW needs to be running (no portable mode) prob. as a service to check the conditions.

**Closed** 2020-07-30 14:01 UTC
Labels: question
