### ISSUE TITLE
bypass simplewall simply with Tor !

### ISSUE THREAD

**Issue by xevapu** [henrypp/simplewall#417] opened 2019-05-08 10:13 UTC
i have run **tor** and enter 127.0.0.1:9150 on windows internet setting (or firefox browser setting)
all traffic bypass simplewall simply without any filtering!

it is seriously bug
[
another same bug](https://github.com/henrypp/simplewall/issues/413).

**Comment by pwn0r** [comment] 2019-05-08 14:28
I think there is an option "allow loopback connections for all". I think you can try to disable it first and see if you can assign localhost rules.

**Comment by xnoreq** [comment] 2019-05-10 18:15
It's not a bug. You don't understand what you're doing or how the firewall is working.

I suggest @henrypp to simply close this issue.

**Closed** 2023-03-21 11:53 UTC

**Comment by thankuverymuch** [comment] 2024-10-21 08:31
Comodo Firewall or Fort Firewall will detect and block programs that attempt to connect to Tor via loopback (127.0.0.1:9150). It seems like you don't understand the concept of a firewall.

**Comment by thankuverymuch** [comment] 2024-10-21 08:31
> It's not a bug. You don't understand what you're doing or how the firewall is working.

Comodo Firewall or Fort Firewall will detect and block programs that attempt to connect to Tor via loopback (127.0.0.1:9150). It seems like you don't understand the concept of a firewall.
