### ISSUE TITLE
Request: Shell extension

### ISSUE THREAD

**Issue by ackys** [henrypp/simplewall#317] opened 2019-02-02 15:47 UTC
Hi there Henry.

The request is for a shell extension to right click an .exe file in explorer and create a custom user rule without opening simplewall window from system tray. Hope you can make it someday. Shell extension rocks as it gives the user an easy way to add custom rules for executable files.

**Comment by henrypp** [comment] 2019-02-03 04:09
Duplicate of #280

**Closed by henrypp** 2019-02-03 04:09 UTC
