### ISSUE TITLE
The app crashes when i try to open the folder of an app (SimpleWall 3.6.2)

### ISSUE THREAD

**Issue by nuno-src** [henrypp/simplewall#1224] opened 2022-04-30 15:24 UTC
The app crashes when i try to open the folder(CTRL+ E) of an app in the apps menu
![image](https://user-images.githubusercontent.com/75589883/166111637-985752e9-e48e-40cc-8832-0d16fdb7630b.png)

![image](https://user-images.githubusercontent.com/75589883/166111552-f0a1f1c1-dc65-4c4e-a821-ebe75d349edf.png)

Then I get this message about the memory reference
If i close this window or click close simplewall shuts down.

Sry for send this prints in portuguese.

**Comment by henrypp** [comment] 2022-05-01 10:42
crashdump?

**Comment by nuno-src** [comment] 2022-05-01 11:29
this message appears (sry the portuguese)
but the same thing happens, the app closes
![image](https://user-images.githubusercontent.com/75589883/166143899-c4fe1a45-9246-44e8-91e5-27560b3b7aa0.png)

**Comment by henrypp** [comment] 2022-05-01 11:33
Try to open manually

**Comment by nuno-src** [comment] 2022-05-01 11:44
I can't find it anywhere

**Comment by gettysburg** [comment] 2022-05-01 17:53
Look for files with the file extension ``.dmp``, if necessary search your entire hard drive.

**Comment by gettysburg** [comment] 2022-05-01 18:24
Look for files with the file extension ``.dmp``, if necessary search your entire hard drive.

Opening Event Viewer (open Start menu, then enter ``eventvwr.msc``), then navigating to ``Windows Logs -> Application``, and finding the crash entry for ``simplewall.exe`` might also provide valuable information (such as the fault address and module).

**Comment by gettysburg** [comment] 2022-05-01 18:28
Look for files with the file extension ``.dmp``, if necessary search your entire hard drive.

Opening Event Viewer (open Start menu, then enter ``eventvwr.msc``), then navigating to ``Windows Logs -> Application``, and finding the crash entry for ``simplewall.exe`` might also provide valuable information (such as the fault address and module).

It is advised that you sort all Event Viewer entries by date and time, and then by severity.

**Comment by nuno-src** [comment] 2022-05-01 18:41
I couldn't find any .dmp file related to simplewall my pc, the Henry++ folder doesn't even exist.
Event viewer does not show anything about simplewall. I even recreated the bug again and nothing was registered

**Comment by gettysburg** [comment] 2022-05-01 19:55
> I even recreated the bug again and nothing was registered.

That is likely because he registers his own exception handler, but please be advised that without a ``.dmp`` file we will not be able to figure out why simplewall crashes.

If you have any experience with debugging Windows applications, you could try to attach a free debugger like [x64dbg](https://x64dbg.com) to simplewall, then trigger the crash and see where the exception is thrown - a screenshot (including the call-stack) would already help us.

**Comment by nuno-src** [comment] 2022-05-01 20:25
I do not have much experience... but is this?
![image](https://user-images.githubusercontent.com/75589883/166163244-f319c93f-eedb-4aeb-b513-990b3a5f3932.png)
![image](https://user-images.githubusercontent.com/75589883/166163283-1cf8dfcf-f92a-4934-9f66-eb2fd144dd8e.png)

**Comment by gettysburg** [comment] 2022-05-02 04:48
Thanks.

I took a short look using IDA, and it seems like ultimately a function responsible for freeing heap allocated memory crashes while dereferencing a pointer / argument passed through parameters, the function that ended up calling this function opens Windows Explorer and selects file (caller of crashing function is screenshot #1, crashing function is #2):

![image](https://user-images.githubusercontent.com/2256003/166185630-0d9f016c-61b4-4fc1-bc06-220483df3d35.png)
![image](https://user-images.githubusercontent.com/2256003/166184477-effbb86c-cc5a-402c-9523-3852679b020a.png)

Highlighted parts of IDA pseudo-code are execution-flow / location of crash in second screenshot.

This makes sense, because you mentioned in your first post that simplewall crashes while you try to open the folder containing the binary of a user rule, and this feature would highlight the binary, which you can do if you pass /select argument to Explorer:

```/select <object> Open a window view with the specified folder, file or application selected.```

@henrypp 

By the way, I just tried to use this option, and it causes the same crash on my system (Windows Server 2019 LTSC), crash dump also does not get created properly (because you try to write file to non-existent folder hierarchy, you have to create Henry++ folder in "AppData\\Roaming" first, then "crashdumps" folder, and then you can write your crash dump file).

I hope my analysis helps to fix the problem, I could not find the two functions above in your public code-base but it is only 06:00 AM where I live and I did not have a coffee yet :-)

**Comment by Pandaa-P** [comment] 2022-05-07 02:42
@gettysburg what steps did you took to crash the app?  opening the folder of an app from app menu does not crash the app for me.

Also I do have `AppData\Roaming\Henry++\simplewall` in AppData\Roaming. Closing the app, deleting it and restarting the app and from the menu choosing "open containing folder" does not crash the app either. 

And we both run windows 10 enterprise ltsc with the same Kernel version.

**Comment by gettysburg** [comment] 2022-05-07 19:50
@Pandaa-P 

I didn't crash it, the screenshot number 2 from nuno-source's provided enough information for me to reverse-engineer it.

> Closing the app, deleting it and restarting the app and from the menu choosing "open containing folder" does not crash the app either.

Weird, indeed - if only right now I wasn't forced to stay and look at / and rewrite around 95% of code per day

> Also I do have AppData\Roaming\Henry++\simplewall in AppData\Roaming.

I don't have an ``AppData\Roaming\Henry++\simplewall`` , yet it works fine.

Seems like the folder hierarchy / crash dumps don't get created sometimes, this is also the reason I asked about the folder hierarchy because that the Windows API will not create it for you if it doesn't exists, look at the ``winbase.h`` header and source file yourself.

**Comment by gettysburg** [comment] 2022-05-07 20:40
@Pandaa-P 

I didn't crash it, the screenshot number 2 from nuno-source provided enough information for me to reverse-engineer it.

> Closing the app, deleting it and restarting the app and from the menu choosing "open containing folder" does not crash the app either.

Weird, I'm guessing that it's some isolated bug here as well.

> Also I do have AppData\Roaming\Henry++\simplewall in AppData\Roaming.

I don't have an ``AppData\Roaming\Henry++\simplewall`` , yet it works fine.

Seems like the folder hierarchy / crash dumps don't get created sometimes, this is also the reason I asked about the folder hierarchy because the Windows API will not create it for you if it doesn't exists, look at the ``winbase.h`` header and source files yourself.

**Comment by Pandaa-P** [comment] 2022-05-07 22:54
>I don't have an AppData\Roaming\Henry++\simplewall , yet it works fine.

Maybe because it save `profile.xml`  and `simplewall.ini` (which is what `AppData\Roaming\Henry++\simplewall` contain) to its installation folder as well. 
in my system I have these two files on "AppData\Roaming\Henry++\simplewall" and on "C:\Program Files\simplewall"

**Closed** 2022-05-10 17:00 UTC
Labels: bug

**Comment by gettysburg** [comment] 2022-05-11 17:27
Still not fixed in Version 3.6.3, now just nothing happens.

**Comment by gettysburg** [comment] 2022-05-12 01:33
Confirmed fixed in Version 3.6.3, no crash.. but I initially did bamboozle myself:

I thought it was still broken when ``explorer.exe`` didn't launch, but that was due to me taking some unneeded permission away from simplewall:

![image](https://user-images.githubusercontent.com/2256003/167910704-f93ddd4a-061a-44aa-bf4c-0e1b548e55d0.png)

So, all good, thanks for the fast fix.
