### ISSUE TITLE
[Bug] After upgrading to v3.8.0 UI is not responding to keyboard inputs.

### ISSUE THREAD

**Issue by jenish2014** [henrypp/simplewall#1754] opened 2024-04-05 17:54 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.0

### Windows version

Windows10 - v19045.4170

### Steps to reproduce

Install via Chocolatey
Upgrade to v3.8.0

### Expected behavior

Dialog box expected to accept keyboard inputs.

### Actual behavior

Dialog box is not responding to keyboard inputs. TAB, Shift-TAB or ALT-F4 keys not working.

**Comment by sn0utss** [comment] 2024-04-18 09:56
I'm on Win10 1809 and am experiencing similar. Main UI and network alert notifications are hanging and only occasionally respond to input. Managed to turn off dark theme but issues persisted. Returning to v.3.7.8, works as normal.

If you have any suggestions for troubleshooting I'd be happy to help. Have used this program for many years and v3.8 is the first I've encountered such a thing.

**Comment by henrypp** [comment] 2024-04-23 17:33
@sn0utss and TS

it is a duplicate of #1760 (and possible fix)

**Closed by henrypp** 2024-04-23 17:33 UTC
Labels: bug

**Comment by brian6932** [comment] 2024-04-23 19:10
Not sure how this is a duplicate of my issue though, mine was about a bind being misinterpreted in the wrong context.

**Comment by henrypp** [comment] 2024-04-23 20:38
@brian6932 anyway,i cant reproduce this issue,and in ur issue is have fix for this (mb).
