### ISSUE TITLE
Command Line Usage

### ISSUE THREAD

**Issue by jjxtra** [henrypp/simplewall#712] opened 2020-07-06 15:15 UTC
Is it possible to use this tool with only the command line? Something like `simplewall.exe -reload myconfig.ini` that simply looks for the ini file and refreshes all the rules without showing the gui? That way we can programmatically modify the .ini file without need of the gui...

Happy to donate for this feature if it doesn't exist.

**Comment by frustreated** [comment] 2020-07-06 20:27
应该可以的吧。源代码公开的，把界面去掉就行了。

**Comment by jjxtra** [comment] 2020-07-06 20:31
The biggest hurdle I am running into is trying to build the code into a .dll. The build process seems "magical". I know there are a couple sub-modules involved, but I don't need most of the code, just the ini parsing and wfp parts.

**Comment by frustreated** [comment] 2020-07-07 01:17
> The biggest hurdle I am running into is trying to build the code into a .dll. The build process seems "magical". I know there are a couple sub-modules involved, but I don't need most of the code, just the ini parsing and wfp parts.

compile this like this
git clone three git (simplewall routine pugixml)to the same directory
and use vs2019 to open simplewall project
then compile it 
everything will be OK

**Comment by henrypp** [comment] 2020-07-10 09:42
this topic is duplicate of #703

**Closed by henrypp** 2020-07-10 09:42 UTC
Labels: duplicate
