### ISSUE TITLE
auto update 3.7.5 fails

### ISSUE THREAD

**Issue by boa-conflictor** [henrypp/simplewall#1655] opened 2023-12-02 10:27 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.5

### Windows version

W10 Pro

### Steps to reproduce

Use update function, or get notified that version 3.7.6 is available

### Expected behavior

Start updating

### Actual behavior

Nothing seems to happen, but when checking in %appdata% >> henry++ >> simplewall >> cache, the 3.7.6 installer is there.

**Comment by herrenP** [comment] 2023-12-06 09:38
Same here. Is it due to #1652?

**Comment by herrenP** [comment] 2023-12-06 09:40
> Same here. Is it due to #1652?

Maybe not. I was able to update using the cached updater.

**Comment by boa-conflictor** [comment] 2023-12-07 01:55
> This has been happening to me too over a number of versions, and continues to happen with v3.7.5(now prompting to update to 3.7.6)


Correct, i had the same, hence i decided to open a ticket about it.
If the cause is persistent, or to time-consuming to solve, maybe it's more easy to refer users to update manual anyway?

**Comment by robcum23** [comment] 2023-12-07 13:33
Same here. It automatically notifies me that update 3.7.6 is available but nothing happens when I choose to update? It stays on version 3.7.5. I'm on Windows 10 Pro

**Comment by unkn000wn** [comment] 2023-12-07 21:06
почему закрыто. Авто обновление так и не работает. Когда исправят и будет работать авто обновление корректно?
why is it closed? Auto update still doesn't work. When will they fix it and will the auto update work correctly?

**Comment by herrenP** [comment] 2023-12-07 21:11
> почему закрыто. Авто обновление так и не работает. Когда исправят и будет работать авто обновление корректно? why is it closed? Auto update still doesn't work. When will they fix it and will the auto update work correctly?

I'm guessing @henrypp closer your ticket (#1662) as a duplicate of this ticket (#1655).

**Comment by boa-conflictor** [comment] 2023-12-10 00:37
> > > почему закрыто. Авто обновление так и не работает. Когда исправят и будет работать авто обновление корректно? why is it closed? Auto update still doesn't work. When will they fix it and will the auto update work correctly?
> > 
> > 
> > I'm guessing @henrypp closed your ticket (#1662) as a duplicate of this ticket (#1655).
> 
> why closed this theme too before i am open again? As far as I know, this bug has been observed for quite a long time. Is it difficult to fix it? On the previous version of OS, before reinstalling Windows, the same behavior was observed. I don’t really remember which version it started with.
> 
> If auto-update doesn’t work, then why is it needed at all? Just remove the functionality from the application so that this message does not pop up every time after a reboot.


Agree, this issue/bug has been around for quite some time now. Hence i opened this issue.

It seems that this issue is persistent, but we better not ask @henrypp, because then he will probably  respond with his infamous remarks....

**Comment by boa-conflictor** [comment] 2023-12-10 00:41
@henrypp your users are blind, stupid, whatever...really?????????????????

**Comment by unkn000wn** [comment] 2023-12-10 14:12
не понятно почему он не исправит очевидный баг который у всех проявляется. неужели это так сложно? Может он нарочно этого не делает?
It’s not clear why it won’t fix the obvious bug that everyone has. is it really that difficult? Maybe he doesn't do this on purpose?

**Comment by boa-conflictor** [comment] 2023-12-11 11:53
> @henrypp your users are blind, stupid, whatever...really?????????????????

Just as expected...the uneducated response :)

**Comment by ridetonirvana** [comment] 2023-12-27 22:53
@henrypp Hey usel3ss cnt fix your trash software, stpid fok

**Comment by henrypp** [comment] 2023-12-27 22:54
@ridetonirvana grfo u idiot

**Comment by ridetonirvana** [comment] 2023-12-27 22:57
fix it mongolian beef, lazy azz fk!

**Comment by magJ** [comment] 2023-12-27 23:06
Can all the people who don’t have anything constructive to add to this discussion, please just fuck off.

It’s crazy how entitled people are about some free software.

**Comment by pralium444** [comment] 2024-01-04 14:21
Never worked for me since the first time i tried this amazing firewall

**Comment by henrypp** [comment] 2024-01-04 22:09
@pralium444 u started using from 3.7+? use latest ver, it is fixed

**Closed** 2024-01-04 22:09 UTC
Labels: bug

**Comment by herrenP** [comment] 2024-01-06 16:12
Updated successfully from 3.7.6 to 3.7.7. Thanks for solving the issue!
