### ISSUE TITLE
[Bug] v. 3.7.1 won't automatically install (win10)

### ISSUE THREAD

**Issue by deroverda** [henrypp/simplewall#1513] opened 2023-08-12 14:08 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.0

### Windows version

10

### Steps to reproduce

Autopop tells me there is a new version available. 
It downloads, asks me if I want to install, I install and nothing happens. 

### Expected behavior

it should automatically update to latest version instead. 

### Actual behavior

the popup install/update windows simply vanished and nothing happens. is it safe to run the setup.exe from your github and all my settings will stay the same? 

### Logs

asdad

**Comment by deroverda** [comment] 2023-08-12 14:10
![simplewall_20230812_0h](https://github.com/henrypp/simplewall/assets/70813982/9f629faa-7bf7-4ec4-bb67-9381e0b981f7)

Here's a .GIF demonstrating the issue.

**Comment by ReflexivR** [comment] 2023-08-12 21:12
I had the same issue.

**Comment by huldf** [comment] 2023-08-13 07:28
Had the same issue, you can execute the setup manually without any problem to update to 3.7.1. Your settings won't be lost.

**Comment by deroverda** [comment] 2023-08-13 13:02
> Had the same issue, you can execute the setup manually without any problem to update to 3.7.1. Your settings won't be lost.

Thanks for replying. I just manually updated and no issues occurred. Hopefully when 3.7.2 is released the automatic update will work.

**Comment by deroverda** [comment] 2023-08-13 13:03
I don't know why my replies automatically closes the issue.

**Comment by huldf** [comment] 2023-08-13 14:16
> Thanks for replying. I just manually updated and no issues occurred. Hopefully when 3.7.2 is released the automatic update will work.

FYI, I just updated simplewall on another computer which had an older version (forgot to check it before but probably one year old) and I had no issues with the automatic update. I assume this issue only occurs when upgrading from 3.7.0 to 3.7.1.

**Comment by maxwood** [comment] 2023-08-17 07:48
Same issue on W11

**Comment by RH-BD** [comment] 2023-08-19 02:52
Same here...

**Comment by RH-BD** [comment] 2023-08-21 05:59
Both automatically and manually download(ed) the the 3.71 update but do not get installed... What to do. Please help.

**Comment by huldf** [comment] 2023-08-21 07:35
> Both automatically and manually download(ed) the the 3.71 update but do not get installed... What to do. Please help.

The manually downloaded setup file should update your app without any issue. Are you using the portable version?

**Comment by RH-BD** [comment] 2023-08-21 12:04
No, I'm not using the portable version. I'm going to help-> Check for updates-> Downloading 3.7.1-> Installing but when I'm check the about it is always 3.7 and then if again repeat the process it is not installing.

**Comment by huldf** [comment] 2023-08-21 19:25
It won't work through the app menu, you have to download the setup.exe file of the new version on GitHub and execute it like you're installing the app for the first time.

**Comment by RH-BD** [comment] 2023-08-22 03:51
It always automatically downloaded. I never had to go manually. Do I need to download it now from the GitHub? What about next time?

**Comment by MysteriousShadow** [comment] 2023-08-23 06:40
Same here. It's always asking me to update to 3.7.1. I click and install -> restart the app -> still asks me to update to 3.7.1

**Comment by jcrevani** [comment] 2023-09-08 14:28
A soon as this release was published in my desktop (Windows 10 pro) the auto update worked just fine  but in my laptop (windows 10 Home) the update failed to install. I installed manually.

**Comment by reddyshyam** [comment] 2023-09-22 07:28
Same issue with 3.7.2. 

I have manually installed both 3.7.1 back then and 3.7.2 now

**Comment by Dark-Noir** [comment] 2023-09-23 03:41
Its maybe because Microsoft SmartScreen blocks the installer by default (because its not known/to new).

**Comment by reddyshyam** [comment] 2023-09-23 04:54
> Its maybe because Microsoft SmartScreen blocks the installer by default (because its not known/to new).

Thanks for the insight but why from 3.7.1 onwards? Actually the installer begins, setup completes but goes no where

**Comment by henrypp** [comment] 2023-09-23 10:34
just manualy install

**Comment by GitCourser** [comment] 2023-10-14 06:16
The same problem,3.71>3.72, now 3.72>3.73, are confirmed after the automatic update but will not update, if this is the system limit, hope to change to update to prompt there is an update (anyway, the download can not be installed), so that their own website to download the new version of the installation.

**Comment by jcrevani** [comment] 2023-10-14 13:33
In my desktop install doesn't close the program, so as Henry suggested I closed Simplewall and manually installed. Maybe next installer will close it before installing.

**Comment by deroverda** [comment] 2023-11-03 13:07
Still having to manually update and not within the update. Not the end of the world really, but it was convenient being able to update through the program. I wonder why this feature doesn't work anymore.

**Comment by huldf** [comment] 2023-11-03 13:36
Also had to manually update, I think the downloaded binary isn't the latest version but the same as the currently installed one.

**Closed** 2023-12-01 17:23 UTC
Labels: bug

**Comment by tagatac** [comment] 2024-02-03 12:41
@henrypp when you close this issue, do you mean that it is not worth fixing?

Thanks for the project!

**Comment by henrypp** [comment] 2024-02-03 12:42
@tagatac it already fixed
